---
Name: "validation-test-fatal"
Description: "Example fatal validation task"
Meta:
  color: "blue"
  icon: "bug"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
Templates:
- Name: "validation_fatal.sh"
  Contents: |
    #!/bin/bash
    # Copyright RackN, 2019

    set -e

    {{ template "setup.tmpl" . }}
    {{ template "validation-lib.tmpl" . }}

    # A fatal task needs immediate attention with possible remediation.
    # Bad network or something like that could be fatal that would
    # succeed without changes to the machine.
    #
    # In this case, do NOT call add_validation_error, just exit 1.
    echo "This is a fatal failure.  Just exit 1."
    exit 1

