---
Name: flash-discover
Description: Detect which system firmware flash method to use.
Prerequisites:
  - hardware-tools-install
Templates:
  - Name: discover
    Contents: |
      #!/usr/bin/env bash
      {{ template "setup.tmpl"  .}}
      mfgr="$(drpcli gohai |jq -r '.DMI | .System | .Manufacturer')"

      APPEND=""
      {{ if .ParamExists "flash-list" }}
      echo "Hardware system, $mfgr, updated by list. Assume list is self-contained."
      APPEND="-list"
      {{ end }}
      case $mfgr in
          "Dell Inc.") drpcli machines tasks add {{.Machine.UUID}} at 0 dell-firmware-flash${APPEND};;
          "HP"|"HPE") drpcli machines tasks add {{.Machine.UUID}} at 0 hpe-firmware-flash${APPEND};;
          Lenovo) drpcli machines tasks add {{.Machine.UUID}} at 0 lenovo-firmware-flash${APPEND};;
          *) echo "No idea how to flash${APPEND} for $mfgr";;
      esac
