---
Name: lab-drp-external-network
Description: Set up the DRP ip forwarding, masquerading, etc.
Documentation: |
  Set up DRP endpoint as an ip forwarding/masquerading gateway for the
  student lab machines.

Meta:
  color: blue
  feature-flags: sane-exit-codes
  icon: shopping cart
  title: RackN Content
OptionalParams: []
Prerequisites: []
Templates:
  - Contents: |-
      #!/usr/bin/env bash
      # Lab DRP network setup

      set -e

      EXT={{ .Param "lab-drp-external-network" }}

      echo "Setting up ip forwaarding ... "
      sysctl net.ipv4.ip_forward=1
      echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/50-ipv4_ip_forward.conf
      echo "Adding MASQUERADING rules for nat translation..."
      iptables -t nat -A POSTROUTING -o $EXT -j MASQUERADE

      echo "Configuring static network on internal eth1 network..."
      #
      echo "
      DEVICE=eth1
      BOOTPROTO=none
      ONBOOT=yes
      PREFIX=24
      IPADDR=192.168.1.1
      " > /etc/sysconfig/network-scripts/ifcfg-eth1
      systemctl restart network

    ID: ""
    Link: ""
    Meta: {}
    Name: "proxmox-lab-network"
    Path: ""
